export default [
  'Villareal CF',
  'Juventus',
  'FC Porto',
  'SL Benfica',
  'Schalke 04',
  'VfL Wolfsburg',
  'Liverpool',
  'Bor. M\'gladbach',
  'FC Barcelona',
  'Sporting CP',
  'Athletic Bilbao',
  'Fiorentina',
  'AS Monaco',
  'Stoke City',
  'Manchester Utd',
  'Inter',
  'Manchester City',
  'Everton',
  'Real Madrid',
  'Roma',
  'Arsenal',
  'Chelsea',
  'Napoli',
  'Olympique Lyon',
  'FC Bayern',
  'Sevilla FC',
  'Bayer 04',
  'AC Milan'
]
